runtime: nodejs16
env: standard
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 3
env_variables:
  PORT: ${PORT}
  DATABASE_URL: ${DATABASE_URL}
  JWT_SECRET: ${JWT_SECRET}
